Articles
HadasKedem/PUBLIC-S.server pull request #6
Opened 2021-07-06 13:17 UTC by HadasKedem

2021-07-06 15:56 UTC, Guyeise1 requested changes
More places where name 'Artifact' is used instead of 'Article'

2021-07-06 15:56 UTC, Guyeise1 commented on src/controllers/ArticleController.ts
>  export class ArtifactController extends AbstractController {
Change the class name

2021-07-06 15:56 UTC, Guyeise1 commented on src/models/Article.ts
> +    field: String
What is this?

2021-07-16 12:09 UTC, OrezriceWasHere commented on src/controllers/ArticleController.ts
>  export class ArtifactController extends AbstractController {
It is changed

2021-07-16 12:10 UTC, OrezriceWasHere commented on src/models/Article.ts
> +    field: String
all fields required for article.

2021-07-16 12:11 UTC, merged